export const GET_QUESTIONS = "GET_QUESTIONS";
export const COMMIT_ANSWER_FORWARD = "COMMIT_ANSWER_FORWARD";
export const GET_RESULTS = "GET_RESULTS";
export const END_QUIZ = "END_QUIZ";
export const COMMIT_ANSWER_BACK = "COMMIT_ANSWER_BACK";
